

// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmKgsOlUmThSCNnD9LjQFx51PmJDkBW0k',
    appId: '1:699022731941:web:66792ccb64ddb2fc8c3b4c',
    messagingSenderId: '699022731941',
    projectId: 'quiz-scheduler-3a295',
    authDomain: 'quiz-scheduler-3a295.firebaseapp.com',
    storageBucket: 'quiz-scheduler-3a295.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf78QtQuUS-t3MnNeXWwO2wViOZ4Q9sKI',
    appId: '1:699022731941:android:ca6f32a98699fc958c3b4c',
    messagingSenderId: '699022731941',
    projectId: 'quiz-scheduler-3a295',
    storageBucket: 'quiz-scheduler-3a295.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsJNBkdohM4g8yB41MxE-LoHLeSTKExXU',
    appId: '1:699022731941:ios:454989dd48c715b98c3b4c',
    messagingSenderId: '699022731941',
    projectId: 'quiz-scheduler-3a295',
    storageBucket: 'quiz-scheduler-3a295.firebasestorage.app',
    iosBundleId: 'com.example.quizScheduler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsJNBkdohM4g8yB41MxE-LoHLeSTKExXU',
    appId: '1:699022731941:ios:454989dd48c715b98c3b4c',
    messagingSenderId: '699022731941',
    projectId: 'quiz-scheduler-3a295',
    storageBucket: 'quiz-scheduler-3a295.firebasestorage.app',
    iosBundleId: 'com.example.quizScheduler',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmKgsOlUmThSCNnD9LjQFx51PmJDkBW0k',
    appId: '1:699022731941:web:3295c0cd0e7df7b18c3b4c',
    messagingSenderId: '699022731941',
    projectId: 'quiz-scheduler-3a295',
    authDomain: 'quiz-scheduler-3a295.firebaseapp.com',
    storageBucket: 'quiz-scheduler-3a295.firebasestorage.app',
  );
}
